import type { Exercise } from "./types";

export const EXERCISES: Exercise[] = [
  /* ── WARM-UP ── */
  { id: 1, c: "חימום", n: "Chromatic 1-2-3-4 Hand Sync", m: 5, b: "80-120", d: "One finger per fret starting at fret 5. Strict alternate picking (Down-Up). Ascend string 6 to 1, descend back, shift up one fret. Minimal fretting pressure, small pick motion.", yt: "chromatic 1234 guitar warm up alternate picking sync", t: "Iron rule: 3 consecutive mistakes = drop 10 BPM. Always with metronome. Cleanliness over speed.", f: "Hand Synchronization, Warm-Up", bt: false, tex: `\\title "Chromatic 1-2-3-4" \\subtitle "Hand Sync Warm-Up" \\tempo 80 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :16 5.6 6.6 7.6 8.6 | 5.5 6.5 7.5 8.5 | 5.4 6.4 7.4 8.4 | 5.3 6.3 7.3 8.3 | 5.2 6.2 7.2 8.2 | 5.1 6.1 7.1 8.1 | 8.1 7.1 6.1 5.1 | 8.2 7.2 6.2 5.2 | 8.3 7.3 6.3 5.3 | 8.4 7.4 6.4 5.4 | 8.5 7.5 6.5 5.5 | 8.6 7.6 6.6 5.6` },
  { id: 2, c: "חימום", n: "Spider Exercise Finger Independence", m: 5, b: "75-95", d: "Fingers 1+3 on one string, 2+4 on the adjacent. Cycle through all string pairs. Switch patterns every minute: 1-3/2-4, then 1-4/2-3, then 2-4/1-3.", yt: "spider exercise guitar finger independence coordination", t: "Speed is irrelevant. Only precision. Keep unused fingers hovering close to the fretboard at all times.", f: "Finger Independence, Cross-String Coordination", bt: false },
  { id: 3, c: "חימום", n: "Legato Warm-Up Am Pentatonic No Pick", m: 5, b: "", d: "Am Pentatonic position 5. Hammer-ons ascending, pull-offs descending. No pick at all. Every note at equal volume. Let your hands fully relax.", yt: "legato warm up Am pentatonic guitar no pick", t: "If you feel tension stop and slow down. This is about release, not challenge. Tension = injury risk.", f: "Muscle Release, Basic Legato", bt: false },
  { id: 4, c: "חימום", n: "Hand Stretching and Injury Prevention", m: 3, b: "", d: "No guitar. Wrist extension (palm forward 15 sec). Wrist flexion (palm back 15 sec). Individual finger bends. Wrist circles 10 sec each direction.", yt: "guitarist hand stretching warm up prevent RSI injury", t: "NON-NEGOTIABLE before every session. Prevents Carpal Tunnel and RSI. Sharp pain = stop immediately.", f: "Injury Prevention, Flexibility", bt: false },
  { id: 5, c: "חימום", n: "Two-Octave Scale Am Pentatonic + Natural Minor", m: 5, b: "60-90", d: "Am Pentatonic then Am Natural Minor, full two octaves. Alternate picking. Slow tempo. Goal: fretboard mapping and hand preparation.", yt: "Am pentatonic natural minor two octaves guitar slow", t: "Start at 60 BPM. Increase only when every note rings clean for 3 consecutive passes.", f: "Fretboard Navigation, Melodic Warm-Up", bt: false, tex: `\\title "Am Pentatonic - 2 Octaves" \\subtitle "Warm-Up Scale Run" \\tempo 60 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :8 5.6 8.6 5.5 7.5 5.4 7.4 5.3 7.3 | 5.2 8.2 5.1 8.1 8.1 5.1 8.2 5.2 | 7.3 5.3 7.4 5.4 7.5 5.5 8.6 5.6` },
  /* ── SHRED ── */
  { id: 6, c: "שרדינג", n: "Alternate Picking Full Pentatonic Speed Build", m: 10, b: "80-165", d: "First 5 min: clean at 3 speeds (60%, 80%, 95%). Last 5 min: push max BPM. Strict Down-Up including string crossings. No economy allowed here.", yt: "alternate picking Am pentatonic speed building metal guitar", t: "3 errors = drop 10 BPM. Log your clean max BPM every session. Progress tracking is what makes this work.", f: "Alternate Picking, Progressive Speed Building", bt: true, styles: ["Metal", "Hard Rock"], tex: `\\title "Alternate Picking Speed Build" \\subtitle "Am Pentatonic" \\tempo 80 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :16 5.6 8.6 5.6 8.6 5.5 7.5 5.5 7.5 | 5.4 7.4 5.4 7.4 5.3 7.3 5.3 7.3 | 5.2 8.2 5.2 8.2 5.1 8.1 5.1 8.1 | 8.1 5.1 8.1 5.1 8.2 5.2 8.2 5.2 | 7.3 5.3 7.3 5.3 7.4 5.4 7.4 5.4 | 7.5 5.5 7.5 5.5 8.6 5.6 8.6 5.6` },
  { id: 7, c: "שרדינג", n: "Sextuplet Pentatonic 3NPS Descending", m: 10, b: "55t-140", d: "Descending: 15-13-12 on each string. Sextuplet = 6 notes per beat. 5 min single string (motor pattern), 5 min full run. Zakk Wylde / Dimebag sound.", yt: "sextuplet pentatonic 3nps descending shred Zakk Wylde", t: "t = Triplet tempo. 55t = ~82 BPM in sixteenths. Consistency over peak speed. Record weekly to track progress.", f: "Sextuplets, Descending Runs, 3NPS", bt: true, styles: ["Metal", "Hard Rock"] },
  { id: 8, c: "שרדינג", n: "Sextuplet Natural Minor 3NPS Hammett", m: 10, b: "50t-120", d: "Am Natural Minor position 12. Three notes per string. Wider stretches than pentatonic. Kirk Hammett signature: One, Blackened, AJFA.", yt: "natural minor 3NPS sextuplet Kirk Hammett Metallica", t: "Start with 2 strings, add one every two days. Your fingers need stretch readiness. Rushing = strain.", f: "3NPS Natural Minor, Hammett Style", bt: true, styles: ["Metal"] },
  { id: 9, c: "שרדינג", n: "Burst Picking Controlled Explosions", m: 8, b: "80-130", d: "4 sixteenth notes at max speed, FULL STOP (complete beat silence), 4 again. Trains burst control the real weapon of shredding. Nobody shreds continuously.", yt: "burst picking guitar speed control short bursts shred", t: "Silence must be absolute. No ringing, no noise. If you cant stop clean youre too fast. Control > raw speed.", f: "Burst Control, Picking Accuracy", bt: false, styles: ["Metal", "Neo-Classical"] },
  { id: 10, c: "שרדינג", n: "Economy Picking Gambale Method", m: 10, b: "70-120", d: "When crossing to a lower string continue same pick direction (down follows down). Eliminates 30% wasted motion. Frank Gambale method. Essential for fast scalar runs.", yt: "economy picking Frank Gambale directional picking guitar", t: "If last note = downstroke and first note on next string = also down, dont reverse. Flow with direction.", f: "Economy Picking, Motion Efficiency", bt: true, styles: ["Jazz", "Neo-Classical"] },
  { id: 11, c: "שרדינג", n: "String Skipping Right Hand Precision", m: 8, b: "60-100", d: "Alternate picking while skipping strings: 6 to 4, 5 to 3, 4 to 2. Forces right hand accuracy. Paul Gilbert, Nuno Bettencourt technique.", yt: "string skipping alternate picking guitar Paul Gilbert", t: "About right-hand accuracy, not speed. Start painfully slow. Missing the string = too fast.", f: "String Skipping, Right Hand Precision", bt: false, styles: ["Metal", "Hard Rock"] },
  /* ── LEGATO ── */
  { id: 12, c: "לגאטו", n: "Basic Legato 2H + 2P Pentatonic", m: 20, b: "80-115", d: "Am Pentatonic: 2 hammer-ons ascending + 2 pull-offs descending per string. Key: every note IDENTICAL volume. Pull-off must sound as loud as hammer-on. Satriani/Vai foundation.", yt: "legato Am pentatonic hammer pull off even volume Satriani", t: "Weak pull-offs? Pull string slightly sideways not just lift. 10 min building + 10 min flow.", f: "Basic Legato, Dynamic Equality", bt: true, styles: ["Hard Rock", "Metal"], tex: `\\title "Basic Legato 2H+2P" \\subtitle "Am Pentatonic" \\tempo 80 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :16 h 5.6 h 8.6 p 8.6 p 5.6 h 5.5 h 7.5 p 7.5 p 5.5 | h 5.4 h 7.4 p 7.4 p 5.4 h 5.3 h 7.3 p 7.3 p 5.3 | h 5.2 h 8.2 p 8.2 p 5.2 h 5.1 h 8.1 p 8.1 p 5.1` },
  { id: 13, c: "לגאטו", n: "Legato Roll Infinite 1-2-4 Pattern", m: 20, b: "70-105", d: "Hammer 1-2-4 each string, pull 4-2-1 descending, continue to next string without stopping. Creates infinite fluid motion. Sounds like no pick exists.", yt: "legato roll 1 2 4 pattern guitar fluid infinite run", t: "10 min slow build (each string separately) + 10 min continuous flow. When it flows you know its working.", f: "Legato Roll, Continuous Flow", bt: true, styles: ["Metal", "Neo-Classical"] },
  { id: 14, c: "לגאטו", n: "Cross-String Legato + Slide Holdsworth", m: 15, b: "65-95", d: "Hammer on one string, slide to adjacent, continue legato. Enables impossibly long runs. Allan Holdsworth / Guthrie Govan territory.", yt: "legato cross string slide Holdsworth Govan long runs", t: "Slide must be seamless. No break in sound. Practice each transition in isolation before connecting.", f: "Cross-String Legato, Holdsworth Style", bt: true, styles: ["Jazz", "Metal"] },
  { id: 15, c: "לגאטו", n: "Legato + Vibrato Musical Endings", m: 12, b: "70-100", d: "Every legato phrase ends with controlled vibrato on the final note. Vibrato transforms technical exercise into musical statement. Without it legato sounds robotic.", yt: "legato vibrato ending note guitar musical phrasing", t: "Vibrato must be CONTROLLED: consistent speed (2-3 Hz) and even width. Random shaking is not vibrato.", f: "Musical Phrasing, Legato + Vibrato", bt: true, styles: ["Hard Rock", "Blues"] },
  { id: 16, c: "לגאטו", n: "Legato + Pick Hybrid 3 Slurred + 1 Picked", m: 12, b: "80-110", d: "Three notes legato + one picked note. Fluid line with rhythmic accents. Picked note punctuates the smoothness. Slash, Petrucci hybrid approach.", yt: "legato pick hybrid 3 plus 1 guitar rock fusion", t: "The picked note is the accent. It should pop slightly louder. This contrast is the entire point.", f: "Hybrid Legato/Pick, Articulation", bt: true, styles: ["Hard Rock", "Metal"] },
  /* ── BENDS + VIBRATO ── */
  { id: 17, c: "בנד", n: "Half-Step Bend Pitch Accuracy", m: 10, b: "60-100", d: "Bend from fret 7 on B string. Play target (fret 8) first as reference, then bend to match. Support bending finger with 3-finger reinforcement.", yt: "half step bend guitar intonation accuracy reference note", t: "Never guess always verify. Play target, listen, bend, compare. Bend accuracy separates amateurs from pros.", f: "Bend Intonation, Pitch Accuracy", bt: false, styles: ["Blues", "Classic Rock"] },
  { id: 18, c: "בנד", n: "Whole-Step Bend Blues/Rock Foundation", m: 10, b: "60-100", d: "Full tone bend fret 7 on G and B strings. The most essential bend in blues/rock. Consistent pressure throughout. Wrist rotation not finger strength.", yt: "whole step bend guitar blues rock wrist rotation", t: "Use whole-hand strength via wrist rotation. 3 fingers behind the bend. Wrist does the work.", f: "Whole-Step Bend, Wrist Mechanics", bt: true, styles: ["Blues", "Classic Rock", "Hard Rock"] },
  { id: 19, c: "בנד", n: "Vibrato Masterclass Gilmour / BB King", m: 12, b: "60-100", d: "Wide slow vibrato on sustained notes. 2-3 oscillations per second. Each wave identical width. Wrist rotation NOT finger trembling. THE hallmark of great players.", yt: "vibrato technique David Gilmour BB King guitar wide slow", t: "Practice against a clock: 1-and-2-and-3 = 3 waves/sec. Consistency over speed. Every great player has great vibrato.", f: "Controlled Vibrato, Wrist Rotation", bt: false, styles: ["Blues", "Classic Rock"] },
  { id: 20, c: "בנד", n: "Unison Bend Hendrix Double-Stop", m: 10, b: "60-100", d: "Two adjacent strings: fretted note on one + bend to same pitch on other. When they meet = natural chorus. Hendrix, SRV, Angus Young.", yt: "unison bend guitar Hendrix SRV Angus Young technique", t: "Both notes must reach identical pitch. Otherwise sounds wrong. Practice each string separately first.", f: "Unison Bend, Classic Rock Essential", bt: true, styles: ["Classic Rock", "Blues", "Hard Rock"] },
  { id: 21, c: "בנד", n: "Pre-Bend + Release Reverse Drama", m: 8, b: "60-100", d: "Bend to target pitch BEFORE picking. Pick the bent note then release slowly. Sound descends dramatically. Blues, metal, country all use this.", yt: "pre bend release guitar technique blues drama reverse", t: "Release must be controlled and even. Practice bending to pitch silently then picking.", f: "Pre-Bend, Dramatic Expression", bt: true, styles: ["Blues", "Metal", "Country"] },
  /* ── TAPPING ── */
  { id: 22, c: "טאפינג", n: "One-Hand Tap Am Arpeggio Van Halen", m: 12, b: "60-100", d: "T-P-H: Tap fret 12 (right hand), pull-off to 7, hammer-on to 5. Am arpeggio. Eddie Van Halen Eruption. Precise sharp tap not heavy strike.", yt: "one hand tapping Am arpeggio Van Halen Eruption TPH", t: "Tap = precise touch not hammer blow. String should not bounce off the fret. Accuracy over force.", f: "Basic Tapping, Van Halen Style", bt: false, styles: ["Hard Rock", "Metal"], tex: `\\title "Tapping Am Arpeggio" \\subtitle "Van Halen Style T-P-H" \\tempo 60 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :16 t 12.2 p 7.2 h 5.2 t 12.2 p 7.2 h 5.2 t 12.2 p 7.2 | h 5.2 t 12.2 p 8.2 h 5.2 t 12.1 p 8.1 h 5.1 t 12.1 | p 8.1 h 5.1 t 12.1 p 8.1 h 5.1 t 12.1 p 8.1 h 5.1` },
  { id: 23, c: "טאפינג", n: "Two-Hand Tapping Extended Range", m: 15, b: "50-90", d: "2 notes left hand + 1 tap right hand high position. Extends range beyond single-hand possibility. Multi-octave arpeggios. Eruption / Midnight.", yt: "two hand tapping extended range Van Halen guitar", t: "Start extremely slowly. Synchronization between hands is the challenge not speed.", f: "Two-Hand Tapping, Extended Range", bt: false, styles: ["Hard Rock", "Metal", "Neo-Classical"] },
  { id: 24, c: "טאפינג", n: "Tapping Arpeggios Over Chord Changes", m: 12, b: "50-80", d: "Tap arpeggios following a chord progression (Am-F-C-G). Each chord gets its own tap pattern. Musical tapping not just technical. Harp-like cascading notes.", yt: "tapping arpeggios chord progression guitar musical", t: "Make it MUSICAL. Follow the chords. Each tap arpeggio outlines the harmony underneath.", f: "Musical Tapping, Harmonic Awareness", bt: true, styles: ["Metal", "Neo-Classical", "Jazz"] },
  /* ── SWEEP ── */
  { id: 25, c: "Sweep", n: "Sweep 3-String Am Arpeggio + Pivot", m: 12, b: "65-115", d: "Single continuous rake across 3 strings. NOT 3 separate downstrokes. Clean pivot at turnaround. Left-hand muting critical for every string you leave.", yt: "sweep picking 3 string Am arpeggio pivot muting", t: "Practice ONLY the pivot turnaround 50 times before the full sweep. The pivot is where sweep lives or dies.", f: "Sweep Fundamentals, Pivot, Muting", bt: false, styles: ["Metal", "Neo-Classical"], tex: `\\title "3-String Am Sweep" \\subtitle "Sweep + Pivot" \\tempo 65 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :16 5.4 5.3 5.2 8.2 5.2 5.3 5.4 5.3 | 5.2 8.2 5.2 5.3 5.4 5.3 5.2 8.2 | 5.2 5.3 5.4 5.3 5.2 8.2 5.2 5.3` },
  { id: 26, c: "Sweep", n: "Sweep 5-String Full Arpeggio + Rolling", m: 15, b: "50-95", d: "Am arpeggio across 5 strings. 5 min down only, 5 min up only, 5 min full. Hardest sweep to clean. Rolling technique required for barred notes.", yt: "sweep picking 5 string Am arpeggio rolling technique", t: "5+5+5. No shortcuts. Rolling: flatten barre finger segment by segment. Dont press all notes at once.", f: "5-String Sweep, Rolling Technique", bt: false, styles: ["Metal", "Neo-Classical"] },
  { id: 27, c: "Sweep", n: "Sweep + Tap Yngwie / Becker Peak", m: 12, b: "45-85", d: "Sweep ascending, tap highest note, pull-off back, sweep descending. Two techniques fused into dramatic statement. Yngwie, Jason Becker.", yt: "sweep picking tap Yngwie Malmsteen Jason Becker", t: "The tap is the dramatic peak. Must land precisely on time. Practice sweep-to-tap transition in isolation.", f: "Sweep+Tap Hybrid, Neo-Classical", bt: false, styles: ["Neo-Classical", "Metal"] },
  /* ── RHYTHM ── */
  { id: 28, c: "קצב", n: "Downpicking Endurance Hetfield Method", m: 10, b: "80-140", d: "Strict downstrokes only. Power chords at sixteenth speed. James Hetfield: Master of Puppets, Blackened. SECRET: picking hand must stay RELAXED.", yt: "downpicking Metallica Hetfield power chords endurance", t: "Biggest mistake: tension. Relax. Let gravity assist. Speed comes from relaxation not force.", f: "Downpicking, Hetfield, Right Hand Relaxation", bt: true, styles: ["Metal"], tex: `\\title "Downpicking Endurance" \\subtitle "Hetfield Method" \\tempo 100 \\instrument 29 \\tuning d2 a2 d3 g3 b3 e4 . :16 d (0.6.0.5) d (0.6.0.5) d (0.6.0.5) d (0.6.0.5) d (2.6.2.5) d (2.6.2.5) d (2.6.2.5) d (2.6.2.5) | d (3.6.3.5) d (3.6.3.5) d (3.6.3.5) d (3.6.3.5) d (0.6.0.5) d (0.6.0.5) d (0.6.0.5) d (0.6.0.5) | d (5.6.5.5) d (5.6.5.5) d (5.6.5.5) d (5.6.5.5) d (3.6.3.5) d (3.6.3.5) d (0.6.0.5) d (0.6.0.5)` },
  { id: 29, c: "קצב", n: "Palm Muting Dynamic Precision", m: 10, b: "", d: "Palm on bridge. 2 bars muted, 2 bars open. This dynamic contrast IS metal rhythm. Hand position on bridge = everything. One millimeter changes the tone.", yt: "palm muting guitar dynamics open muted metal riff", t: "Too close to neck = dead. Too far on bridge = not muted enough. Find YOUR sweet spot.", f: "Palm Muting, Dynamic Control", bt: true, styles: ["Metal", "Hard Rock", "Punk Rock"] },
  { id: 30, c: "קצב", n: "Galloping Iron Maiden D-U-D", m: 10, b: "80-140", d: "Down-Up-Down (two sixteenths + one eighth). The Trooper, Run to the Hills, Number of the Beast. Easy to learn, brutal on endurance.", yt: "galloping rhythm Iron Maiden Trooper DUD pattern", t: "First and third downstrokes = equal volume. Middle upstroke slightly softer. That difference creates the gallop.", f: "Galloping, Iron Maiden, Endurance", bt: true, styles: ["Metal", "Hard Rock"] },
  { id: 31, c: "קצב", n: "Odd Time 7/8 and 5/4 Progressive", m: 12, b: "60-90", d: "7/8: count 1-2-3, 1-2, 1-2 (3+2+2). Feels like something missing. Tool, Meshuggah, Dream Theater, King Crimson.", yt: "odd time 7/8 5/4 guitar Tool Meshuggah progressive", t: "Count out loud first. Tap foot on 1. When you feel the groove physically stop counting. Instinct.", f: "Odd Time, Polyrhythm, Progressive", bt: true, styles: ["Metal", "Jazz"] },
  { id: 32, c: "קצב", n: "Syncopation and Groove Playing the AND", m: 12, b: "70-100", d: "Accent off-beats (the AND between beats). Creates groove and swing. Without syncopation rhythm guitar sounds stiff and robotic.", yt: "syncopation rhythm guitar upbeat groove offbeat accent", t: "Record WITH and WITHOUT syncopation on the same riff. The difference is night and day. Groove lives in offbeats.", f: "Syncopation, Groove, Rhythmic Feel", bt: true, styles: ["Funk", "Blues", "Hard Rock"] },
  /* ── FRETBOARD ── */
  { id: 33, c: "גריף", n: "CAGED System 5 Shapes One Fretboard", m: 15, b: "", d: "5 Am shapes based on open chord forms: C-A-G-E-D. Each has chord voicing AND scale pattern. Connecting all 5 = the entire neck as one playground.", yt: "CAGED system guitar 5 shapes Am chord scale fretboard", t: "One shape per week. Start E Shape (pos 0) and A Shape (pos 5). Connect those two first.", f: "CAGED System, Fretboard Architecture", bt: false },
  { id: 34, c: "גריף", n: "Note Recognition Mental Map", m: 15, b: "", d: "Pick random note (e.g. F#). Find EVERY occurrence on all 6 strings frets 1-12. Use octave patterns. Same note appears ~6 times per octave span.", yt: "fretboard note recognition all positions guitar memorize", t: "One note per day. After 12 days all notes covered. One month of daily practice = fretboard is yours.", f: "Note Recognition, Mental Map", bt: false },
  { id: 35, c: "גריף", n: "Position Shifting 5 Pentatonic Boxes", m: 15, b: "50-80", d: "Am Pentatonic through all 5 positions with slides. Goal: seamless transitions. Listener hears ONE long line not 5 separate boxes.", yt: "Am pentatonic 5 positions connecting sliding guitar", t: "Slide on finger 1 or 4 as bridge. Transition must be INVISIBLE to the listener.", f: "Position Shifting, Fretboard Freedom", bt: true },
  { id: 36, c: "גריף", n: "Triad Shapes Major + Minor All Inversions", m: 15, b: "", d: "Am and C triads in ALL inversions on string groups 1-2-3, 2-3-4, 3-4-5. Root position, 1st inversion, 2nd inversion. Triads = secret weapon of advanced players.", yt: "guitar triad shapes major minor inversions all positions", t: "Triads unlock chord-tone soloing, arpeggiated riffs, and voice-leading. Small shapes massive musical power.", f: "Triads, Inversions, Harmonic Knowledge", bt: false },
  /* ── EAR TRAINING ── */
  { id: 37, c: "אוזן", n: "Interval Recognition musictheory.net", m: 15, b: "", d: "Use musictheory.net/exercises/ear-interval to drill interval recognition. Start with P4, P5, octave. Add m3, M3, m7 over time. Foundation of ALL ear training.", yt: "interval recognition ear training guitar exercises", t: "Link: musictheory.net/exercises/ear-interval. Do 20 reps daily. Start 3 intervals add one per week. 2 months = hear everything.", f: "Interval Recognition, Ear Foundation", bt: false },
  { id: 38, c: "אוזן", n: "Chord Quality Recognition Maj/Min/Dim/7", m: 15, b: "", d: "Use musictheory.net/exercises/ear-chord to identify chord types. Major=happy, Minor=sad, Dim=tense, Dom7=bluesy. Start Major vs Minor only.", yt: "chord quality ear training major minor diminished", t: "Link: musictheory.net/exercises/ear-chord. This skill lets you figure out songs instantly. 15 reps daily.", f: "Chord Recognition, Harmonic Ear", bt: false },
  { id: 39, c: "אוזן", n: "Drone Exercise Tension vs Resolution", m: 15, b: "", d: "Play backing drone on A. Play one note, stop, FEEL: Resolution (root/fifth=stable) or Tension (seconds/sevenths=pull). Dont think. Feel. This is where musicality lives.", yt: "drone note ear training guitar tension resolution feel", t: "The MOST important ear exercise. When you FEEL tension/resolution you become a musician not just a guitarist.", f: "Tension/Resolution, Musical Feeling", bt: true },
  { id: 40, c: "אוזן", n: "Scale Identification Which Mode musictheory.net", m: 10, b: "", d: "Use musictheory.net/exercises/ear-scale to identify scales by ear. Natural minor vs Dorian vs Phrygian. Train ear to recognize modal colors.", yt: "scale identification ear training modes guitar", t: "Link: musictheory.net/exercises/ear-scale. Connects to mode practice. Hear the mode before you play it.", f: "Scale/Mode Recognition", bt: false },
  { id: 41, c: "אוזן", n: "Transcription 8 Bars by Ear No Tab", m: 15, b: "", d: "Choose 8 bars from a solo you love. Slow down (YouTube 0.5x). Find every note. NO TAB. Fastest way to develop ear and vocabulary simultaneously.", yt: "transcribing guitar solo by ear step by step", t: "Start with simple vocal melodies then graduate to solos. One transcription per week = transformation in 3 months.", f: "Transcription, Active Listening", bt: false },
  { id: 42, c: "אוזן", n: "Target Note Soloing Chord Tone Landing", m: 20, b: "", d: "Over backing track: Bar 1=land on Root, Bar 2=3rd, Bar 3=5th, Bar 4=b7. Everything between is free. PLAN landing note BEFORE playing.", yt: "target note soloing chord tones guitar improvisation", t: "Plan the destination before the journey. Intentional playing = professional playing. Record and review.", f: "Chord Tone Targeting, Intentional Soloing", bt: true },
  /* ── IMPROVISATION ── */
  { id: 43, c: "אילתור", n: "Pentatonic Jam Backing Track + Record", m: 15, b: "70-120", d: "Am backing track. Improvise ONLY Am Pentatonic. No memorized licks. React to the music. RECORD yourself. Listen back same day. What worked? What felt forced?", yt: "Am blues rock backing track guitar improvisation", t: "RECORD every improvisation. Listen back same day. Self-review is where all the growth happens. No exceptions.", f: "Free Improv, Self-Recording, Pentatonic", bt: true, styles: ["Blues", "Classic Rock"] },
  { id: 44, c: "אילתור", n: "Chord Tone Navigation Over Changes", m: 20, b: "70-120", d: "Backing track with changes (Am-F-C-G). On each chord change LAND on a chord tone (Root, 3rd, or 5th). Between landing notes play freely. This is how pros navigate.", yt: "chord tone improvisation over changes guitar targeting", t: "Start by landing Root of each chord. When comfortable target 3rd. Then 5th. This alone transforms your solos.", f: "Chord Tone Navigation, Smart Soloing", bt: true, styles: ["Jazz", "Blues"] },
  { id: 45, c: "אילתור", n: "Triad-Based Soloing Small Shapes Big Sound", m: 15, b: "70-120", d: "Over backing track solo using ONLY triad shapes of the current chord. Am chord = Am triad notes. Creates melodic harmonically aware lines that outline changes.", yt: "triad soloing guitar chord tones small shapes melodic", t: "Triads force you to play HARMONY not just scale. This is the difference between scale-running and actual soloing.", f: "Triad Soloing, Harmonic Awareness", bt: true, styles: ["Jazz", "Blues", "Funk"] },
  { id: 46, c: "אילתור", n: "Call and Response Sing First Then Play", m: 15, b: "70-120", d: "Over backing: SING/HUM a 2-bar phrase. Then PLAY that exact phrase on guitar. If you cant sing it you cant play it musically. Forces melodic thinking.", yt: "call response guitar sing first then play improvisation", t: "BB King rule: if you cant sing it dont play it. Kills the habit of running patterns. Builds MELODIES.", f: "Call + Response, Melodic Thinking", bt: true, styles: ["Blues", "Classic Rock"] },
  { id: 47, c: "אילתור", n: "One-String Improv Limitation = Freedom", m: 10, b: "70-120", d: "Improvise over backing using ONLY ONE STRING. Forces phrasing, bends, vibrato, dynamics. Cant hide behind shapes. Pure musical expression.", yt: "one string improvisation guitar limitation phrasing", t: "Try B string first (most vocal). Use bends slides vibrato dynamics. Fewer notes more MUSIC. Record it.", f: "Single-String Improv, Phrasing Focus", bt: true, styles: ["Blues", "Classic Rock"] },
  { id: 48, c: "אילתור", n: "Modal Improv Color Exploration", m: 15, b: "70-120", d: "Pick mode from dashboard. Drone on tonic. Improvise focusing on CHARACTERISTIC NOTE. Dorian=M6, Phrygian=b2, Lydian=#4. Make the color OBVIOUS.", yt: "modal improvisation guitar characteristic note color", t: "Spend first 2 min playing ONLY the characteristic note over drone. HEAR its color. Then build phrases around it.", f: "Modal Improvisation, Color Expression", bt: true, styles: ["Jazz", "Metal"] },
  /* ── RIFFS ── */
  { id: 49, c: "ריפים", n: "Riff Composition ABAC Structure", m: 25, b: "80-140", d: "5 min: choose groove. 5 min: find root. 10 min: build ABAC (A=main, B=variation, A=return, C=ending). 5 min: refine and RECORD final version.", yt: "write guitar riff ABAC structure metal songwriting", t: "A=hook, B=surprise, A=familiar, C=closer. Powers 90% of great riffs. ALWAYS record your final version.", f: "Riff Composition, ABAC, Recording", bt: true, styles: ["Metal", "Hard Rock"] },
  { id: 50, c: "ריפים", n: "Riff Variation Change ONE Element", m: 15, b: "80-140", d: "Take existing riff. Change ONE thing: rhythm, one note, dynamics, or articulation. Record BEFORE and AFTER. Listen to difference.", yt: "improve guitar riff variation one element songwriting", t: "ONE change only. Too many = new riff not improvement. Record both versions. Train your editing ear.", f: "Riff Editing, Variation, Self-Critique", bt: true },
  { id: 51, c: "ריפים", n: "Style Riff Weekly Genre Challenge", m: 20, b: "80-140", d: "Write 4 bars ABAC in this weeks style + mode (from dashboard). Doom=space/half-time, Thrash=sixteenths/palm-mute, Death=tremolo/blast. RECORD.", yt: "write guitar riff doom thrash metal style mode", t: "Same notes sound different in each style. Rhythm dynamics and articulation define genre. Style = delivery.", f: "Style Writing, Genre Challenge, Recording", bt: true, styles: ["Metal", "Hard Rock", "Stoner Rock"] },
  { id: 52, c: "ריפים", n: "Chromatic Riff Heavy Dissonance", m: 15, b: "80-140", d: "Build riff using chromatic half-step movement. Open E + chromatic walk. Black Sabbath, Slayer, Meshuggah. Heaviness through dissonance and tension.", yt: "chromatic heavy riff Sabbath Slayer guitar dissonance", t: "Chromatic movement creates unease. Resolution back to root = payoff. Tension then release. Record it.", f: "Chromatic Riffing, Dissonance", bt: true, styles: ["Metal", "Stoner Rock"] },
  /* ── LICKS + PHRASES ── */
  { id: 53, c: "פרזינג", n: "Zakk Wylde Pentatonic Box Sextuplet", m: 15, b: "60-120", d: "12-15-12 repeating per string (sextuplet) then full descending run. 5 min clean, 5 min speed, 5 min over backing. Add pinch harmonics.", yt: "Zakk Wylde pentatonic box lick sextuplet descending", t: "Repeating sextuplet = buzzsaw. Pinch harmonics at the end = full Zakk mode. Aggression is key.", f: "Zakk Wylde Lick, Pinch Harmonics", bt: true, styles: ["Metal", "Hard Rock"] },
  { id: 54, c: "פרזינג", n: "Kirk Hammett Natural Minor Descending Rain", m: 15, b: "60-120", d: "17-15-12 descending each string. Am Natural Minor. The famous run from One, AJFA, MOP. Practice alternate picking AND legato versions.", yt: "Kirk Hammett descending run natural minor Metallica", t: "Alternate = sharp aggressive. Legato = smooth flowing. Know both. Use each when appropriate.", f: "Hammett Style, Descending Runs", bt: true, styles: ["Metal"] },
  { id: 55, c: "פרזינג", n: "Dorian Lick Major 6th Signature", m: 15, b: "60-120", d: "Am Dorian: frets 5-7-9 on G. Fret 9 = F# = Major 6th = THE note distinguishing Dorian from Aeolian. Brightness inside minor.", yt: "Dorian mode lick guitar major sixth characteristic", t: "EMPHASIZE the Major 6th. Linger. Add vibrato. This one note gives Dorian its identity.", f: "Dorian Mode, Major 6th, Modal Color", bt: true, styles: ["Jazz", "Blues", "Funk"] },
  { id: 56, c: "פרזינג", n: "Phrygian Lick b2 Dark Descent", m: 15, b: "60-120", d: "Am Phrygian position 12. Fret 13 = Bb = b2 = darkest note. Half-step above Root = maximum tension. Doom, Flamenco. Chromatic fall b2 to Root = drama.", yt: "Phrygian lick b2 dark descending doom flamenco guitar", t: "b2 = half-step above Root = maximum tension. Resolve to Root for dramatic payoff. Own this sound.", f: "Phrygian Mode, b2 Darkness", bt: true, styles: ["Metal", "Flamenco"] },
  /* ── MODES ── */
  { id: 57, c: "מודוסים", n: "Mode of the Week 3 Positions + Color", m: 20, b: "60-100", d: "Selected mode in 3 fretboard positions. 5 min each slowly. LISTEN to color. Aeolian=sad, Dorian=jazzy, Phrygian=dark, Lydian=dreamy, Mixolydian=bluesy.", yt: "guitar modes 3 positions fretboard color character", t: "LISTEN dont count. Each mode is a MOOD. Cant hear difference? Play Aeolian then switch. Contrast reveals.", f: "Modal Practice, Color Recognition", bt: true },
  { id: 58, c: "מודוסים", n: "Blues Scale 5 Positions + Blue Note Bend", m: 15, b: "60-95", d: "Am Pentatonic + b5 (Eb) = Blues Scale. b5 = Blue Note = blues flavor. BEND Blue Note up half-step for most authentic sound.", yt: "blues scale 5 positions guitar blue note b5 bending", t: "Blue Note is PASSING tone. Dont camp on it. Bend to 5th or slide through. Color not destination.", f: "Blues Scale, Blue Note Application", bt: true, styles: ["Blues", "Classic Rock"] },
  { id: 59, c: "מודוסים", n: "Mode Comparison Same Root Three Colors", m: 15, b: "60-100", d: "Over Am drone play: Aeolian (b6), Dorian (natural 6), Phrygian (b2). Same root completely different emotion. One note changes EVERYTHING.", yt: "comparing modes same root Aeolian Dorian Phrygian guitar", t: "Aeolian=b6 (sadness). Dorian=natural 6 (optimistic minor). Phrygian=b2 (dark threat). One note = new world.", f: "Mode Comparison, Characteristic Notes", bt: true },
  /* ── CREATION ── */
  { id: 60, c: "יצירה", n: "Record + Review Weekly Self-Assessment", m: 15, b: "", d: "Record 2-3 min of improvisation or song section. Listen back IMMEDIATELY. Write: 3 things that worked + 3 to improve. This is how professionals grow.", yt: "record yourself guitar improve review self assessment", t: "Recording doesnt lie. It shows exactly where you are. Do weekly minimum. Save recordings for monthly comparison.", f: "Self-Recording, Critical Listening", bt: true },
  { id: 61, c: "יצירה", n: "Melody Writing 4-Bar Singable Theme", m: 20, b: "", d: "Write a 4-bar melody you can SING. If you cant sing it its not a melody its a technical passage. Voice first then guitar. Simple memorable emotional. Record.", yt: "melody writing guitar singable theme composition simple", t: "Greatest melodies are SIMPLE. Smoke on the Water. Iron Man. Enter Sandman. Complexity is easy. Simplicity is genius.", f: "Melody Writing, Singability, Composition", bt: true },
  { id: 62, c: "יצירה", n: "Song Section Arrangement Intro/Verse/Chorus", m: 30, b: "", d: "Combine riff (verse) + variation (pre-chorus) + contrasting section (chorus). Dynamics: verse=muted/quiet, chorus=open/loud. Record full arrangement.", yt: "guitar arrangement intro verse chorus songwriting", t: "CONTRAST between sections makes a song. Quiet/loud, muted/open, low/high. Record every arrangement.", f: "Song Arrangement, Structure, Contrast", bt: true },
  { id: 63, c: "יצירה", n: "Riff-a-Day 60-Second Creation", m: 5, b: "", d: "Timer: 60 seconds. Create a riff from scratch. ANY riff. Record on phone immediately. Dont judge dont edit just CREATE. Daily habit.", yt: "write guitar riff fast 60 seconds daily challenge", t: "Quantity breeds quality. Dont wait for inspiration. Create daily. Most riffs = mediocre. Some = gold. Thats the process.", f: "Daily Creation, Speed Composition", bt: false },
  { id: 64, c: "יצירה", n: "Loop Your Own Backing Track + Solo Over It", m: 20, b: "", d: "Record simple chord progression or riff (4-8 bars). Loop it. Then improvise/solo over YOUR OWN backing track. Creating your own musical context.", yt: "create backing track loop guitar record solo improvise", t: "Playing over your own loops = fundamentally different from YouTube tracks. You hear YOUR sound YOUR timing YOUR feel.", f: "Self-Backing, Loop Creation, Full Musicianship", bt: true },
  /* ── DYNAMICS ── */
  { id: 65, c: "דינמיקה", n: "Pick Attack Mastery ff / mf / pp", m: 12, b: "", d: "Same phrase 3 times: ff (very loud), mf (medium), pp (very soft). Same notes completely different story. This separates player from machine.", yt: "pick attack dynamics guitar fortissimo pianissimo", t: "Dynamics = 50% of expression. One volume = flat and boring. Master this and transform your sound.", f: "Dynamic Control, Pick Attack", bt: true },
  { id: 66, c: "דינמיקה", n: "Volume Swells Violin / Ambient Texture", m: 10, b: "", d: "Volume to zero. Pick note. Gradually raise volume. No-attack sound like violin. Powerful for ambient doom atmospheric passages. Pink Floyd territory.", yt: "volume swell guitar violin ambient no attack effect", t: "Volume knob (classic) or pedal (practical). Dark amp + heavy reverb = cinematic atmosphere.", f: "Volume Swells, Ambient Texture", bt: true, styles: ["Metal", "Classic Rock"] },
  { id: 67, c: "דינמיקה", n: "Phrasing and Silence The Power of Space", m: 15, b: "", d: "Every phrase ends with deliberate silence (full beat minimum). Spaces between notes are as important as notes. BB King, Gilmour, Slash masters of NOT playing.", yt: "guitar phrasing silence space BB King Gilmour", t: "BB King: if you cant sing what youre playing youre playing too many notes. Silence IS music. Less = more.", f: "Phrasing, Silence, Musical Space", bt: true, styles: ["Blues", "Classic Rock"] },
  /* ── CHORDS ── */
  { id: 68, c: "אקורדים", n: "Power Chord Transitions Speed Drill", m: 10, b: "80-140", d: "Power chords moving across fretboard: E5-A5-D5-G5. Strict downstrokes. Clean transitions no buzzing. Palm mute between chords. Foundation of ALL rock/metal rhythm.", yt: "power chord transitions speed drill metal guitar", t: "Lift fingers just enough to move. Dont fly off the fretboard. Economy of motion = speed.", f: "Power Chords, Transitions, Rhythm Foundation", bt: true, styles: ["Metal", "Hard Rock", "Punk Rock"] },
  { id: 69, c: "אקורדים", n: "Barre Chord Marathon E and A Shapes", m: 15, b: "60-100", d: "E-shape and A-shape barre chords through common progressions: I-IV-V-I in multiple keys. Full barre pressure. Clean ring on all strings. The most important chord skill.", yt: "barre chord practice guitar E shape A shape progression", t: "Press with the SIDE of your index finger not the flat. Thumb behind neck. If strings buzz isolate which one.", f: "Barre Chords, E/A Shapes, Chord Progressions", bt: true },
  { id: 70, c: "אקורדים", n: "Seventh Chord Voicings Jazz/Blues Foundation", m: 12, b: "", d: "Maj7, min7, dom7, m7b5 voicings. Shell voicings (Root-3rd-7th) on strings 6-4-3 and 5-4-3. Foundation for blues comping and jazz. Small shapes massive harmonic power.", yt: "seventh chord voicings guitar jazz blues shell voicings", t: "Shell voicings = Root + 3rd + 7th. Thats all you need to define any chord quality. Learn these in all 12 keys.", f: "7th Chords, Shell Voicings, Jazz/Blues Harmony", bt: false, styles: ["Jazz", "Blues"] },
  { id: 71, c: "אקורדים", n: "Chord Switching Metronome Challenge", m: 10, b: "40-80", d: "Two chords. Switch on beat 1. Start at 40 BPM in half notes. Add 5 BPM when clean for 8 bars. Track your max clean BPM. Works for ANY chord pair you struggle with.", yt: "chord switching speed metronome practice guitar", t: "Pick your WORST chord change and attack it daily. One clean switch at 80 BPM beats 100 sloppy ones at 120.", f: "Chord Transitions, Metronome Practice, Precision", bt: false },
  { id: 72, c: "אקורדים", n: "Sus and Add Chords Embellishment Tricks", m: 10, b: "", d: "Add9, sus2, sus4 as embellishments over basic chords. Hendrix-style: add pinky to barre chord for sus4 then release. Creates movement within static chords.", yt: "sus chords add9 guitar embellishment Hendrix style", t: "These are the chords that make rhythm guitar INTERESTING. One finger addition transforms a boring chord into magic.", f: "Sus/Add Chords, Hendrix Style, Chord Embellishment", bt: false, styles: ["Classic Rock", "Funk"] },
  /* ── HARMONICS ── */
  { id: 73, c: "הרמוניקס", n: "Natural Harmonics Bell Tones Frets 5-7-12", m: 10, b: "", d: "Touch string lightly DIRECTLY above fret wire (not between frets). Frets 12 7 5 are strongest. Lift finger immediately after picking. Crystal bell tones.", yt: "natural harmonics guitar fret 5 7 12 technique", t: "Common mistake: pressing too hard. Touch like a feather directly above the fret wire. Bridge pickup + pick near bridge = clearest tone.", f: "Natural Harmonics, Touch Technique", bt: false },
  { id: 74, c: "הרמוניקס", n: "Pinch Harmonics Zakk Wylde Squealies", m: 12, b: "", d: "Thumb edge touches string immediately after pick attack. Sweet spots vary per string position. Heavy distortion required. Zakk Wylde Billy Gibbons signature sound.", yt: "pinch harmonics technique Zakk Wylde guitar squeals", t: "Find YOUR sweet spots: pick at different positions between neck and bridge pickup. Each spot produces different pitch. Map them.", f: "Pinch Harmonics, Zakk Wylde, Sweet Spots", bt: false, styles: ["Metal", "Hard Rock"] },
  { id: 75, c: "הרמוניקס", n: "Artificial Harmonics Lenny Breau Style", m: 10, b: "", d: "Fret any note with left hand. Right hand index finger touches 12 frets above while thumb or ring finger picks. Creates harmonics from ANY fretted note. Advanced technique.", yt: "artificial harmonics guitar technique Lenny Breau", t: "Right hand must be precisely 12 frets above left hand position. Even 1mm off kills the harmonic. Practice on one string first.", f: "Artificial Harmonics, Advanced Technique", bt: false, styles: ["Jazz", "Acoustic"] },
  { id: 76, c: "הרמוניקס", n: "Tap Harmonics Eddie Van Halen", m: 8, b: "", d: "Fret a note. Tap sharply with right hand 12 frets above. Creates chiming harmonic. Can tap 7 or 5 frets above for different intervals. Van Halen spanish guitar intro.", yt: "tap harmonics guitar Van Halen technique", t: "Tap SHARPLY and bounce off immediately. The tap must be precise on the fret wire. Combine with natural harmonics for cascading chimes.", f: "Tap Harmonics, Van Halen, Chime Effects", bt: false, styles: ["Hard Rock", "Metal"] },
  { id: 77, c: "הרמוניקס", n: "Harmonic Melody Creating Music with Harmonics", m: 10, b: "", d: "Play a simple melody using ONLY harmonics: natural at 12-7-5 plus artificial. Combines all harmonic types into musical expression. Think intro to Roundabout by Yes.", yt: "harmonic melody guitar Yes Roundabout harmonics musical", t: "Map which notes are available as natural harmonics first. Fill gaps with artificial harmonics. Creates ethereal otherworldly sound.", f: "Harmonic Melody, Musical Application, All Types", bt: false, styles: ["Classic Rock", "Acoustic"] },
  /* ── PICKING STYLES ── */
  { id: 78, c: "פיקינג", n: "Fingerpicking PIMA Basic Patterns", m: 15, b: "50-80", d: "Thumb (P) on bass strings 4-5-6. Index (I) string 3. Middle (M) string 2. Ring (A) string 1. Basic pattern: P-I-M-A ascending then P-A-M-I descending. Foundation of all fingerstyle.", yt: "fingerpicking PIMA pattern guitar beginner acoustic", t: "Each finger is assigned a string. NEVER deviate until the pattern is automatic. Consistency before creativity.", f: "PIMA Fingerpicking, Finger Assignment, Foundation", bt: false, styles: ["Acoustic", "Flamenco"] },
  { id: 79, c: "פיקינג", n: "Travis Picking Alternating Bass + Melody", m: 15, b: "60-90", d: "Thumb alternates between two bass strings (beat 1 and 3). Fingers play melody on treble strings (beat 2 and 4). Independence between thumb and fingers. Merle Travis Chet Atkins.", yt: "Travis picking guitar alternating bass melody beginner", t: "Thumb is on AUTOPILOT. It never stops alternating. Melody floats on top. Practice thumb pattern alone for 5 min first.", f: "Travis Picking, Thumb Independence, Country/Folk", bt: false, styles: ["Country", "Acoustic"] },
  { id: 80, c: "פיקינג", n: "Hybrid Picking Pick + Fingers Simultaneously", m: 12, b: "70-110", d: "Hold pick normally. Use middle and ring fingers to pluck higher strings. Enables arpeggiated lines impossible with pick alone. Essential for country fusion and modern rock.", yt: "hybrid picking guitar pick and fingers technique", t: "Middle finger = string 2 or 3. Ring finger = string 1 or 2. Keep pick grip relaxed. Start with simple chord arpeggios.", f: "Hybrid Picking, Pick+Fingers, Modern Technique", bt: false, styles: ["Country", "Funk", "Hard Rock"] },
  { id: 81, c: "פיקינג", n: "Economy Picking Across Scale Patterns", m: 12, b: "70-120", d: "When crossing to adjacent string continue pick direction (down to lower string = keep going down). Eliminates wasted motion. Frank Gambale method applied to full scales.", yt: "economy picking scales guitar Frank Gambale directional", t: "Different from alternate picking ONLY at string crossings. Within a string its identical. The transition is where economy happens.", f: "Economy Picking, Directional Picking, Efficiency", bt: true, styles: ["Jazz", "Neo-Classical"] },
  { id: 82, c: "פיקינג", n: "Chicken Picking Country Snap", m: 10, b: "80-120", d: "Pick downstroke on bass string then snap treble string with middle finger. Creates percussive twangy sound. Country essential but used in funk and rock too. Brad Paisley Danny Gatton.", yt: "chicken picking guitar country snap technique", t: "The SNAP is key. Pull the string slightly away from the body then release. Should hear a percussive pop. Clean tone or light overdrive.", f: "Chicken Picking, Country Technique, Percussive", bt: true, styles: ["Country", "Funk"] },
  /* ── ARPEGGIOS ── */
  { id: 83, c: "ארפג'יו", n: "Major and Minor Triad Arpeggios All String Groups", m: 15, b: "60-100", d: "Am and C major triads in root position 1st and 2nd inversion across string groups: 1-2-3 then 2-3-4 then 3-4-5. Alternate picking. Connects to CAGED shapes.", yt: "triad arpeggios all inversions guitar string groups", t: "These small 3-note shapes are the building blocks of EVERYTHING. Chord tones in solos riff writing and harmony.", f: "Triad Arpeggios, Inversions, All String Groups", bt: false },
  { id: 84, c: "ארפג'יו", n: "Seventh Chord Arpeggios Maj7 Min7 Dom7", m: 15, b: "55-95", d: "Four-note arpeggios: Cmaj7 Am7 G7 patterns across the neck. Two octaves. Alternate picking then legato. Foundation for jazz and fusion soloing.", yt: "seventh chord arpeggios guitar maj7 min7 dom7", t: "Know which arpeggio fits over which chord. Maj7 over I and IV. Min7 over ii iii vi. Dom7 over V. This IS harmonic soloing.", f: "7th Arpeggios, Harmonic Soloing, Jazz Foundation", bt: true, styles: ["Jazz", "Neo-Classical"] },
  { id: 85, c: "ארפג'יו", n: "String Skipping Arpeggios Wide Intervals", m: 12, b: "50-90", d: "Skip strings to create wide interval arpeggios. Play root on string 6 then 3rd on string 4 then 5th on string 2. Creates angular modern sound. Paul Gilbert technique.", yt: "string skipping arpeggios guitar wide intervals Paul Gilbert", t: "Right hand accuracy is everything. Missing the target string = too fast. Practice the skip motion slowly in isolation.", f: "String Skipping, Wide Arpeggios, Angular Lines", bt: false, styles: ["Metal", "Hard Rock"] },
  { id: 86, c: "ארפג'יו", n: "Arpeggio Sequences Over Chord Changes", m: 15, b: "60-100", d: "Play matching arpeggio over each chord in a progression: Am7 arp over Am7 chord then Dm7 arp over Dm7 then G7 arp over G7. Arpeggios FOLLOW the harmony.", yt: "arpeggio over chord changes guitar practice progression", t: "This is how jazz musicians navigate changes. Each chord gets its own arpeggio. Connect them smoothly with common tones or half steps.", f: "Arpeggio Navigation, Chord Changes, Jazz Approach", bt: true, styles: ["Jazz", "Blues"] },
  /* ── SLIDE ── */
  { id: 87, c: "סלייד", n: "Slide Guitar Basics Open E Tuning", m: 15, b: "", d: "Open E tuning (E-B-E-G#-B-E). Slide on ring finger. Hover directly above fret wire not between frets. Light pressure. Mute behind slide with trailing fingers.", yt: "slide guitar basics open E tuning beginner technique", t: "Three rules: 1) Directly above fret wire for intonation. 2) Light pressure. 3) ALWAYS mute strings behind the slide with trailing fingers.", f: "Slide Basics, Open E, Intonation", bt: false, styles: ["Blues", "Classic Rock"] },
  { id: 88, c: "סלייד", n: "Slide Blues Licks Elmore James Style", m: 12, b: "", d: "Classic slide blues vocabulary: slide into notes from below. Vibrato by shaking slide rapidly. Target chord tones. Elmore James Duane Allman Derek Trucks territory.", yt: "slide blues licks guitar Elmore James Duane Allman", t: "Slide vibrato = rapid back and forth motion around the target fret. Width and speed define your slide voice. Listen to Derek Trucks.", f: "Slide Blues, Vibrato, Classic Licks", bt: true, styles: ["Blues", "Classic Rock"] },
  { id: 89, c: "סלייד", n: "Standard Tuning Slide Technique", m: 12, b: "", d: "Slide in standard tuning. Harder than open tuning but more versatile. Must be precise with intonation. Muting non-target strings is critical. Joey Landreth Sonny Landreth.", yt: "slide guitar standard tuning technique tips", t: "Standard tuning slide requires surgical precision. Mute strings you are not playing with both hands. Practice single-string melodies first.", f: "Standard Tuning Slide, Precision, Versatility", bt: false, styles: ["Blues", "Country"] },
  /* ── TUNINGS ── */
  { id: 90, c: "כיוונים", n: "Drop D Essential Metal Tuning", m: 12, b: "80-140", d: "Tune low E down to D. Enables one-finger power chords on bottom 3 strings. ESSENTIAL for metal and hard rock. Killswitch Engage Lamb of God Foo Fighters.", yt: "drop D tuning guitar metal riffs exercises technique", t: "Check tuning with harmonic: 12th fret of dropped string should match 7th fret of A string. One-finger power chords change everything.", f: "Drop D, One-Finger Power Chords, Metal Essential", bt: true, styles: ["Metal", "Hard Rock", "Grunge"] },
  { id: 91, c: "כיוונים", n: "Drop C Heavy Low Tuning Riffs", m: 12, b: "70-130", d: "Drop D then everything down one whole step (C-G-C-F-A-D). Heavier darker sound. Thicker strings recommended (11-54 minimum). System of a Down Deftones As I Lay Dying.", yt: "drop C tuning guitar heavy riffs exercises", t: "Thicker strings are MANDATORY for low tunings. Standard 9s will be floppy and unplayable. 11-54 or 12-56 for Drop C.", f: "Drop C, Heavy Tuning, String Gauge", bt: true, styles: ["Metal", "Stoner Rock"] },
  { id: 92, c: "כיוונים", n: "Open G Tuning Keith Richards Style", m: 12, b: "", d: "D-G-D-G-B-D. Classic Rolling Stones sound. Keith Richards removes low E string entirely. Barre across all strings = major chord. Slide friendly tuning.", yt: "open G tuning guitar Keith Richards Rolling Stones", t: "In open G strumming open strings = G major chord. Barre at any fret = that frets major chord. Instant songwriting tool.", f: "Open G, Rolling Stones, Alternate Tuning", bt: false, styles: ["Classic Rock", "Blues"] },
  { id: 93, c: "כיוונים", n: "DADGAD Celtic and Modern Fingerstyle", m: 12, b: "", d: "D-A-D-G-A-D. Neither major nor minor. Suspended ethereal sound. Jimmy Page Kashmir. Modern acoustic fingerstyle. Let open strings ring for huge sound.", yt: "DADGAD tuning guitar acoustic fingerstyle Celtic", t: "The beauty of DADGAD is the open strings creating drones. Let everything ring. Explore what happens when you fret single notes against open strings.", f: "DADGAD, Celtic, Fingerstyle, Drone", bt: false, styles: ["Acoustic", "Classic Rock"] },
  /* ── KEYBOARD ── */
  { id: 94, c: "קלידים", n: "Keyboard Note Identification", m: 10, b: "", d: "A piano key is highlighted on a 2-octave keyboard (C3-B4). Identify the note name. Builds fundamental note recognition on the keyboard layout. White keys and black keys.", yt: "piano keyboard note identification beginner", t: "Black keys are grouped in 2s and 3s. C is always to the left of the 2 black keys. Use visual patterns.", f: "Note Recognition, Piano Layout", bt: false },
  { id: 95, c: "קלידים", n: "Keyboard Interval Identification", m: 12, b: "", d: "Two piano keys are highlighted on the keyboard. Identify the interval between them. Visual + aural interval training using the keyboard layout.", yt: "piano interval identification visual keyboard", t: "Count the half-steps between highlighted keys. White key to white key isn't always the same interval. Learn the pattern.", f: "Interval Recognition, Keyboard Visual", bt: false },
  { id: 96, c: "קלידים", n: "Keyboard Scale Identification", m: 12, b: "", d: "A set of piano keys is highlighted forming a scale pattern. Identify which scale it is. Visual pattern recognition of scales on the keyboard.", yt: "piano scale identification visual patterns", t: "Major scales have a specific pattern of whole and half steps. Look for the half-step positions (E-F, B-C) as landmarks.", f: "Scale Recognition, Keyboard Patterns", bt: false },
  { id: 97, c: "קלידים", n: "Keyboard Chord Identification", m: 12, b: "", d: "Piano keys forming a chord are highlighted. Identify the chord quality (Major, Minor, Dim, etc.). Visual chord recognition on the keyboard.", yt: "piano chord identification visual keyboard", t: "Major chord = root + 4 half-steps + 3 half-steps. Minor = root + 3 + 4. Count the gaps between highlighted keys.", f: "Chord Recognition, Keyboard Voicing", bt: false },
  { id: 98, c: "קלידים", n: "Keyboard Ear Training", m: 15, b: "", d: "A note is played. Click the correct key on the piano keyboard. Combines ear training with keyboard spatial awareness. Develops absolute pitch sense.", yt: "piano ear training click correct key", t: "Start with just the white keys (C major). When comfortable add black keys. Use reference notes to orient yourself.", f: "Ear Training, Piano, Absolute Pitch", bt: false },
  { id: 100, c: "ריפים", n: "Beginner Blues — 12 Bar Shuffle in E", m: 10, b: "60", d: "Classic 12-bar blues shuffle in E. Double-stop pattern on low strings with E5-A5-B7-A7 progression. From Marty Music Chapter 7. Develops shuffle feel and blues rhythm foundation.", yt: "12 bar blues shuffle guitar beginner E", t: "Keep the shuffle feel loose and swinging. The rest before each double-stop is what creates the groove. Mute unused strings with palm.", f: "Blues Shuffle, 12-Bar Form, Double Stops", bt: true, styles: ["Blues", "Classic Rock"], tex: `\\title "Beginner Blues" \\subtitle "12-Bar Shuffle in E — Marty Music Ch.7" \\tempo 90 \\ts 12 8 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :8 r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | r (0.5 2.4) (0.5 2.4) r (0.5 4.4) (0.5 4.4) r (0.5 5.4) (0.5 5.4) r (0.5 4.4) (0.5 4.4) | r (0.5 2.4) (0.5 2.4) r (0.5 4.4) (0.5 4.4) r (0.5 5.4) (0.5 5.4) r (0.5 4.4) (0.5 4.4) | r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | r (0.6 2.5) (0.6 2.5) r (0.6 4.5) (0.6 4.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) | (2.6 1.5 2.4 0.3 2.2).4 (2.6 1.5 2.4 0.3 2.2).8 (2.6 1.5 2.4 0.3 2.2).4 (2.6 1.5 2.4 0.3 2.2).8 (2.6 1.5 2.4 0.3 2.2).4 (2.6 1.5 2.4 0.3 2.2).8 | (0.5 2.4 0.3 2.2 0.1).4 (0.5 2.4 0.3 2.2 0.1).8 (0.5 2.4 0.3 2.2 0.1).4 (0.5 2.4 0.3 2.2 0.1).8 (0.5 2.4 0.3 2.2 0.1).4 (0.5 2.4 0.3 2.2 0.1).8 | r (0.6 2.5) (0.6 2.5) r (0.6 5.5) (0.6 5.5) r (0.6 4.5) (0.6 4.5) r (0.6 3.5) (0.6 3.5) r (0.6 2.5) (0.6 2.5) | 0.6.8 1.6.8 2.6.8 (2.6 1.5 2.4 0.3 2.2).4. (2.6 0.5 2.4 1.3 2.2).4.` },
  { id: 99, c: "חימום", n: "EXAMPLE EX — Am Pentatonic 1st Position", m: 5, b: "120", d: "Am Pentatonic scale in 1st position (frets 5-8). Ascending all 6 strings then descending. Two notes per string. Repeat 99x for muscle memory.", yt: "Am pentatonic 1st position guitar exercise", t: "Keep all fingers close to the fretboard. Use strict alternate picking. Start slow and build speed gradually.", f: "Pentatonic Scale, 1st Position", bt: false, styles: ["Metal", "Hard Rock", "Blues"], tex: `\\title "Am Pentatonic 1st Position" \\subtitle "Ascending & Descending" \\tempo 120 \\instrument 30 \\tuning e2 a2 d3 g3 b3 e4 . :8 5.6 8.6 5.5 7.5 5.4 7.4 5.3 8.3 | 5.2 8.2 5.1 8.1 5.1 7.1 5.1 r | 5.1 7.1 5.2 8.2 5.2 7.2 5.3 8.3 | 5.3 7.3 5.4 7.4 5.5 8.5 5.6 r` },
  /* ── TAPPING ADVANCED ── */
  { id: 101, c: "טאפינג", n: "Two-Hand Tapping Arpeggios", m: 10, b: "80-140", d: "Tap arpeggios using both hands: left hand frets root and 3rd, right hand taps 5th and octave. Am shape: fret 5 (A), fret 9 (C#), tap 12 (E), tap 17 (A). Creates wide interval cascading lines impossible with one hand. Van Halen meets Satriani.", yt: "two hand tapping arpeggios guitar Van Halen technique", t: "Left hand stays planted. Right hand does the traveling. Tap directly ON the fret wire for clean notes. Mute unused strings with palm.", f: "Two-Hand Tapping, Arpeggio Shapes, Wide Intervals", bt: true, styles: ["Hard Rock", "Neo-Classical"] },
  { id: 102, c: "טאפינג", n: "Multi-Finger Tapping 3-Finger", m: 10, b: "60-100", d: "Use index, middle, and ring fingers of the right hand for tapping. Enables rapid triplet patterns and piano-like runs across strings. Stanley Jordan, Tosin Abasi, TJ Helmerich territory. Start on one string then expand.", yt: "multi finger tapping 3 finger guitar technique advanced", t: "Practice each right-hand finger individually first. Index is strongest, ring is weakest. Build ring finger independence before combining all three.", f: "Multi-Finger Tapping, Piano-Style Guitar, Advanced", bt: false, styles: ["Neo-Classical", "Jazz"] },
  /* ── SWEEP ADVANCED ── */
  { id: 103, c: "Sweep", n: "5-String Sweep Am Shape", m: 10, b: "50-100", d: "Full 5-string Am arpeggio sweep: strings 5 through 1 ascending, then descending. Single continuous pick motion in each direction. The quintessential sweep picking exercise. Yngwie, Jason Becker, Jeff Loomis.", yt: "5 string sweep picking Am arpeggio guitar exercise", t: "One fluid arm motion NOT individual picks. Each note must ring clearly then mute as you leave. Roll your fretting finger at the barre.", f: "5-String Sweep, Am Arpeggio, Full Sweep", bt: false, styles: ["Neo-Classical", "Metal"] },
  { id: 104, c: "Sweep", n: "Economy + Sweep Combo Lines", m: 10, b: "60-120", d: "Combine economy picking within a scale with sweep picking through arpeggio shapes. Transition seamlessly between scalar runs and swept arpeggios in one phrase. Frank Gambale concept applied to metal/neo-classical context.", yt: "economy picking sweep picking combo guitar Frank Gambale", t: "The transition point between economy and sweep is where most players stumble. Practice the 2-3 notes around each transition in isolation.", f: "Economy-Sweep Hybrid, Seamless Transitions", bt: true, styles: ["Neo-Classical", "Metal"] },
  /* ── MODES ADVANCED ── */
  { id: 105, c: "מודוסים", n: "Phrygian Dominant Metal Apps", m: 10, b: "70-120", d: "Phrygian Dominant (5th mode of Harmonic Minor): 1-b2-3-4-5-b6-b7. The b2+M3 interval creates exotic Middle Eastern tension. Marty Friedman, Al Di Meola. Apply over V chord in minor keys for authentic neo-classical sound.", yt: "Phrygian Dominant mode guitar metal Middle Eastern", t: "The M3 is what separates this from regular Phrygian. Emphasize the b2-to-M3 augmented second interval. That IS the sound.", f: "Phrygian Dominant, Exotic Metal, Harmonic Minor", bt: true, styles: ["Metal", "Neo-Classical"] },
  { id: 106, c: "מודוסים", n: "Lydian Mode Floating Sound", m: 10, b: "60-90", d: "Lydian mode: Major scale with #4. Creates a floating, ethereal, dreamlike quality. Steve Vai signature sound. Joe Satriani Flying in a Blue Dream. Play over a major chord drone and let the #4 create that suspended-in-air feeling.", yt: "Lydian mode guitar Steve Vai floating dreamy technique", t: "The #4 wants to resolve up to 5. Resist resolving. Let it float. Thats the Lydian magic. Use clean tone with delay.", f: "Lydian Mode, #4 Sound, Ethereal Quality", bt: true, styles: ["Hard Rock", "Jazz"] },
  { id: 107, c: "מודוסים", n: "Modal Shifting 7 Modes", m: 10, b: "70-100", d: "Play all 7 modes from the same root note (e.g., A Ionian, A Dorian, A Phrygian, A Lydian, A Mixolydian, A Aeolian, A Locrian). Same root, different colors. Hear how each mode transforms the emotional landscape over the same drone.", yt: "all 7 modes same root guitar parallel modes comparison", t: "Play each mode for 30 seconds then switch. The contrast between modes is where the learning happens. Record yourself playing through all 7.", f: "Parallel Modes, All 7 Modes, Color Comparison", bt: true },
  /* ── DYNAMICS ── */
  { id: 108, c: "דינמיקה", n: "Crescendo Decrescendo Waves", m: 5, b: "80-120", d: "Play a repeated phrase (e.g., open E power chord pattern) and gradually increase volume from ppp to fff over 4 bars, then decrease back to ppp over 4 bars. Continuous wave. Picking hand controls everything. Develops dynamic range.", yt: "guitar dynamics crescendo decrescendo exercise picking", t: "Think of it as a wave. Smooth transitions not sudden jumps. Your picking distance from the string controls volume. Small motion=quiet, large motion=loud.", f: "Dynamic Range, Crescendo, Decrescendo", bt: false },
  { id: 109, c: "דינמיקה", n: "Ghost Notes Funk Rhythm", m: 10, b: "70-100", d: "Play a funk rhythm pattern where most notes are ghost notes (muted, barely audible) with accented notes popping out. Creates groove and pocket. Nile Rodgers, John Frusciante, Cory Wong. The unheard notes create the feel.", yt: "ghost notes funk guitar rhythm Nile Rodgers technique", t: "Ghost notes are felt not heard. Lightly touch the strings without pressing down. Accented notes should POP against the ghost note backdrop.", f: "Ghost Notes, Funk Rhythm, Dynamic Contrast", bt: true, styles: ["Funk", "Blues"] },
  { id: 110, c: "דינמיקה", n: "Accent Displacement", m: 10, b: "80-120", d: "Play sixteenth notes on a single pitch. Move the accent to different positions: 1-and-2-and, then e-and-a-and, then shifting the accent by one sixteenth each bar. Creates rhythmic illusions and metric modulation feel. Meshuggah concept simplified.", yt: "accent displacement guitar sixteenth notes rhythm exercise", t: "Keep the underlying sixteenth notes perfectly even. ONLY the accent moves. If the base rhythm wobbles the exercise fails. Use metronome always.", f: "Accent Displacement, Metric Illusion, Rhythmic Control", bt: false, styles: ["Metal"] },
  /* ── RHYTHM ADVANCED ── */
  { id: 111, c: "קצב", n: "Double Bass Sync Picking", m: 10, b: "100-180", d: "Synchronize alternate picking with double bass drum pattern. Start at 100 BPM sixteenth notes. Pick and kick drum hit simultaneously. Develops tight metal rhythm playing where guitar and drums lock as one instrument. Essential for modern metal.", yt: "double bass drum sync guitar picking metal exercise", t: "Start with quarter notes synced to kick. Then eighths. Then sixteenths. Speed comes from sync not effort. If pick and kick drift apart slow down.", f: "Double Bass Sync, Metal Rhythm, Tight Playing", bt: true, styles: ["Metal"] },
  /* ── SHRED ── */
  { id: 112, c: "שרדינג", n: "Pedal Point Shred Vinnie Moore", m: 10, b: "80-160", d: "Pedal point technique: alternate between a fixed high note and descending scale tones. E string fret 12 as pedal, B string descends chromatically. Vinnie Moore, Yngwie, Paul Gilbert. Creates dramatic tension between static and moving notes.", yt: "pedal point shred guitar Vinnie Moore Yngwie technique", t: "The pedal note must be EXACTLY the same volume and timing every time. The descending notes provide the melody. Precision on the pedal note is everything.", f: "Pedal Point, Shred Technique, Vinnie Moore", bt: true, styles: ["Neo-Classical", "Metal"] },
  /* ── PICKING ADVANCED ── */
  { id: 113, c: "פיקינג", n: "Tremolo Picking Speed Build", m: 8, b: "100-200", d: "Single string tremolo picking: start at comfortable speed and build 5 BPM per minute. 8 minutes total. Pick as many notes as possible on one string with minimal motion. The ultimate picking speed builder. Foundation for thrash and death metal rhythm.", yt: "tremolo picking speed building guitar exercise metal", t: "Minimal pick motion is the secret. Large motions = slow. Tiny controlled motions = fast. Relax the hand. Tension kills speed.", f: "Tremolo Picking, Speed Building, Minimal Motion", bt: false, styles: ["Metal"] },
  /* ── ARPEGGIO ADVANCED ── */
  { id: 114, c: "ארפג'יו", n: "Diminished Arpeggio Symmetry", m: 10, b: "60-120", d: "Diminished 7th arpeggios are symmetrical: every note is a minor 3rd apart. One shape works from 4 different starting frets. Learn one shape, transpose by 3 frets, same fingering. Covers the entire neck with one pattern. Neo-classical and jazz essential.", yt: "diminished arpeggio symmetry guitar neo-classical jazz", t: "Because of the symmetry there are only 3 unique diminished arpeggios (starting on C, C#, D). Everything else is an inversion. Mind-blowing efficiency.", f: "Diminished Arpeggios, Symmetric Patterns, Fretboard Coverage", bt: false, styles: ["Neo-Classical", "Jazz"] },
  /* ── CHORDS ADVANCED ── */
  { id: 115, c: "אקורדים", n: "CAGED Barre Transitions", m: 10, b: "60-100", d: "Play the same chord (e.g., C major) in all 5 CAGED shapes moving up the neck. C shape (open), A shape (fret 3), G shape (fret 5), E shape (fret 8), D shape (fret 10). Unlocks the entire fretboard for rhythm playing.", yt: "CAGED system barre chords guitar all 5 shapes", t: "Some shapes are harder than others. G shape barre is brutal. Start with E and A shapes which are most common. Add the others gradually.", f: "CAGED System, Barre Chords, Fretboard Navigation", bt: false },
  /* ── SLIDE ADVANCED ── */
  { id: 116, c: "סלייד", n: "Slide Vibrato Intonation", m: 8, b: "60-90", d: "Focus purely on slide vibrato and intonation. Play single notes with slide, holding each for 4 beats. Slide must be directly above fret wire. Add vibrato by oscillating the slide back and forth evenly. Derek Trucks masterclass.", yt: "slide guitar vibrato intonation Derek Trucks technique", t: "Intonation is everything with slide. If you are even 1mm off it sounds wrong. Use your ears not your eyes. Reference each note against a fretted version.", f: "Slide Vibrato, Intonation Precision, Derek Trucks", bt: false },
  /* ── SONGS ── */
  { id: 117, c: "שירים", n: "Song Deconstruction Analysis", m: 15, b: "", d: "Pick any song you love. Break it down: what key? What chords? What scale is the melody using? Where are the hooks? How does the arrangement build? Transcribe the main riff by ear. Understanding song construction makes you a better writer and player.", yt: "song analysis deconstruction guitar music theory apply", t: "Start with simple songs (AC/DC, Nirvana) before tackling complex ones. Write down your analysis. Key, chords, structure, hooks, dynamics.", f: "Song Analysis, Ear Transcription, Music Theory Application", bt: false },
  /* ── LEGATO ADVANCED ── */
  { id: 118, c: "לגאטו", n: "Legato Scale Runs Satriani", m: 10, b: "80-140", d: "Full scale legato runs using hammer-ons and pull-offs exclusively. No picking except the first note of each string. 3 notes per string, all 6 strings. Satriani smooth legato sound. Every note must be equal volume despite no pick attack.", yt: "legato scale runs guitar Satriani smooth technique", t: "Pull-offs are harder than hammer-ons. Practice pull-offs in isolation. The pulling finger must snap sideways not lift off. Equal volume is the goal.", f: "Legato Scale Runs, Satriani Style, Even Volume", bt: true, styles: ["Hard Rock", "Neo-Classical"] },
  /* ── BEND ADVANCED ── */
  { id: 119, c: "בנד", n: "Multi-Step Bends 1.5+2 Tone", m: 8, b: "60-90", d: "Go beyond standard whole-step bends. Practice 1.5 tone (3 fret) and 2 tone (4 fret) bends. Fret 7 on G string bend to fret 10 target (1.5) then fret 11 target (2 tone). Extreme bends used by Gilmour, Jeff Beck, SRV for dramatic expression.", yt: "multi step bend guitar 1.5 tone 2 tone extreme technique", t: "These bends require serious finger strength. Use 3-finger reinforcement always. If it hurts STOP. Build gradually over weeks not days.", f: "Multi-Step Bends, Extreme Bending, Finger Strength", bt: true, styles: ["Blues", "Hard Rock"] },
  /* ── CREATION ADVANCED ── */
  { id: 120, c: "יצירה", n: "Backing Track Creation Layers", m: 15, b: "", d: "Build a complete backing track from scratch in layers: 1) Record rhythm guitar (4-8 bars). 2) Add bass line. 3) Add lead melody or harmony guitar. 4) Structure into sections. Full arrangement thinking. Use the studio or a looper pedal.", yt: "create guitar backing track layers arrangement home studio", t: "Start simple: power chords, basic bass root notes, simple melody. Complexity comes from layering not from individual part difficulty.", f: "Backing Track Creation, Layering, Full Arrangement", bt: false },
];
